### ISSUE TITLE
Nagios Install fails, Requires apt-get update

### ISSUE THREAD

**Issue by robottaway** [networklore/nelmon#1]
Hi,

I setup a Vagrant box with Trusty 14.04 server this morning to install Nagios via your ansible playbook. I ran into one issue which is that an ```apt-get update``` is required before it can properly obtain updates from security.ubuntu.com. Maybe something to do with POODLE? Anyhow would it make sense to have this as part of the playbook anyhow? I figure it's always best to ```apt-get update``` prior to doing major install work like this anyhow.

cheers,
Rob

**Comment by ogenstad** [comment]
Well, it took a while but I've updated the file now. Again, thanks for reporting the issue!
