### ISSUE TITLE
nm-check-certificate-expiration.ps1 - Output Missing All Certs

### ISSUE THREAD

**Issue by selleryp** [networklore/nelmon#7]
Hi,

I am trying to use the nm-check-certificate-expiration.ps1 script to flag up expired certs on locla servers.
I am using Op5 to call the script and appear to have it working, only the output I get when running the script locally on the server differs to when I run it from Op5.

On the server I get the following:

PS C:\Program Files\NSClient++\scripts> C:\Program Files\NSClient++\scripts\nm-check-certificate-expiration-all.ps1
EXPIRED OU=www.verisign.com/CPS Incorp.by Ref. LIABILITY LTD.(c)97 VeriSign, OU=VeriSign International Server CA - Class 3, OU="VeriSign
, Inc.", O=VeriSign Trust Network expired 25/10/2016 00:59:59
EXPIRED CN=Microsoft Windows Hardware Compatibility, OU=Microsoft Corporation, OU=Microsoft Windows Hardware Compatibility Intermediate 
CA, OU=Copyright (c) 1997 Microsoft Corp. expired 31/12/2002 07:00:00
EXPIRED CN=UKCA05, DC=eu, DC=tigplc, DC=com expired 20/04/2015 09:50:50
EXPIRED CN=UKCA4, DC=eu, DC=tigplc, DC=com expired 21/04/2017 09:17:53
EXPIRED CN=UKCA05, DC=eu, DC=tigplc, DC=com expired 22/09/2012 09:47:16
EXPIRED CN=caap1, DC=ap, DC=tigplc, DC=com expired 23/09/2014 09:08:07
EXPIRED CN=cauk1, DC=eu, DC=tigplc, DC=com expired 12/09/2009 12:04:54
EXPIRED CN=cauk1, DC=eu, DC=tigplc, DC=com expired 12/09/2010 12:19:14
EXPIRED CN=CAUK2, DC=eu, DC=tigplc, DC=com expired 10/11/2011 10:11:01
EXPIRED CN=caglobal, DC=tigplc, DC=com expired 21/04/2017 09:17:53
EXPIRED CN=caap1, DC=ap, DC=tigplc, DC=com expired 23/09/2014 09:08:07
EXPIRED CN=cauk1, DC=eu, DC=tigplc, DC=com expired 17/08/2009 11:13:45
EXPIRED CN=Microsoft Authenticode(tm) Root Authority, O=MSFT, C=US expired 31/12/1999 23:59:59
EXPIRED OU=Copyright (c) 1997 Microsoft Corp., OU=Microsoft Time Stamping Service Root, OU=Microsoft Corporation, O=Microsoft Trust Netw
ork expired 30/12/1999 23:59:59
EXPIRED OU="NO LIABILITY ACCEPTED, (c)97 VeriSign, Inc.", OU=VeriSign Time Stamping Service Root, OU="VeriSign, Inc.", O=VeriSign Trust 
Network expired 07/01/2004 23:59:59
EXPIRED OU=Class 3 Public Primary Certification Authority, O="VeriSign, Inc.", C=US expired 07/01/2004 23:59:59
EXPIRED CN=caglobal, DC=tigplc, DC=com expired 23/09/2014 09:08:07
EXPIRED CN=caglobal, DC=tigplc, DC=com expired 16/08/2012 16:36:36
EXPIRED CN=caglobal, DC=tigplc, DC=com expired 21/04/2017 09:17:53
EXPIRED OU=Class 3 Public Primary Certification Authority, O="VeriSign, Inc.", C=US expired 07/01/2004 23:59:59

However in Op5 i get the following:

[root@POLLER custom]# /opt/plugins/check_nrpe -H TESTSERVER -c check_certificate_expiration
EXPIRED OU=www.verisign.com/CPS Incorp.by Ref. LIABILITY LTD.(c)97 VeriSign, OU=VeriSign International Server CA - Class 3, OU="VeriSign, Inc.", O=VeriSign Trust Network expired 25/10/2016 00:59:59
EXPIRED CN=Microsoft Windows Hardware Compatibility, OU=Microsoft Corporation, OU=Microsoft Windows Hardware Compatibility Intermediate CA, OU=Copyright (c) 1997 Microsoft Corp. expired 31/12/2002 07:00:00
EXPIRED CN=UKCA05, DC=eu, DC=tigplc, DC=com expired 20/04/2015 09:50:50
EXPIRED CN=UKCA4, DC=eu, DC=tigplc, DC=com expired 21/04/2017 09:17:53
EXPIRED CN=UKCA05, DC=eu, DC=tigplc, DC=com expired 22/09/2012 09:47:16
EXPIRED CN=caap1, DC=ap, DC=tigplc, DC=com expired 23/09/2014 09:08:07
EXPIRED CN=cauk1, DC=eu, DC=tigplc, DC=com expired 12/09/2009 12:04:54
EXPIRED CN=cauk1, DC=eu, DC=tigplc, DC=com expired 12/09/2010 12:19:14
EXPIRED CN=CAUK2, DC=eu, DC=tigplc, DC=com expired 10/11/2011 10:11:01
EXPIRED CN=caglobal, DC=tigplc, DC=com expired 21/04/2017 09:17:53
EXPIRED CN=caap1, DC=ap, DC=tigplc, DC=com expired 23

I have amended the scripts default cert directory $CERTDIR = "Cert:\LocalMachine\My" so that it will check not just certs in the personal store, but all stores.

I have amened this to: 
$CERTDIR = "Cert:\LocalMachine\CA","Cert:\LocalMachine\Root","Cert:\LocalMachine\My","Cert:\LocalMachine\TrustedPublisher","Cert:\LocalMachine\ClientAuthIssuer","Cert:\LocalMachine\Remote Desktop","Cert:\LocalMachine\TrustedDevices","Cert:\LocalMachine\AuthRoot","Cert:\LocalMachine\TrustedPeople","Cert:\LocalMachine\SmartCardRoot","Cert:\LocalMachine\Trust","Cert:\LocalMachine\Disallowed","Cert:\LocalMachine\REQUEST"

I am wondering if there is a limit to how many Op5 will display, but conversations with them aren't too helpful as this is a 3rd party plugin that they don't support.

Any help I can get with this would be great.

Thanks,
Paul

**Comment by ogenstad** [comment]
I hope you aren't paying too much for support for OP5. ;)

Looks like the check_nrpe client cuts the output after 1024 characters. This should be a setting in the client or nrpe server.

However I would suggest that you just delete the old certificates and the problem will go away.

**Comment by selleryp** [comment]
Thanks for the feedback Patrick.
After I proved that the script ran successfully using nscp.exe test on the server but differed when ran through Op5, they were happier to look into the issue and confirmed the same findings are you.

I have deleted the older certs and all looks to be working as expected.

Thanks,
Paul
